--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/wolfie/Pulpit/Osobiste/Tapety/pawel-czerwinski-mQ9ITEx3L-c-unsplash.jpg"

-- Special
background="#121414"
foreground="#d5dede"
cursor="#e3e2e2"

-- Colors
color0="#121414"
color1="#9fb0b1"
color2="#c7c7dc"
color3="#8ae2f8"
color4="#bedbdc"
color5="#8af5fa"
color6="#93fcd5"
color7="#bafd89"
color8="#acb4b4"
color9="#abbabb"
color10="#cecee0"
color11="#9ce5f9"
color12="#c7dfe0"
color13="#9df6fa"
color14="#a4fcda"
color15="#c3fe9b"
